export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const PROJECTS_REQUEST = "PROJECTS_REQUEST";
export const PROJECTS_SUCCESS = "PROJECTS_SUCCESS";
export const PROJECTS_FAILED = "PROJECTS_FAILED";
export const PROJECT_COMMENT = "PROJECT_COMMENT";
export const PROJECT_TRACK = "PROJECT_TRACK";
export const PROJECT_TRACK_SUCCESS = "PROJECT_TRACK_SUCCESS";

export const ISSUES_REQUEST = "ISSUES_REQUEST";
export const ISSUES_SUCCESS = "ISSUES_SUCCESS";
export const ISSUES_FAILED = "ISSUES_FAILED";
export const ISSUES_HIDE = "ISSUES_HIDE";
export const ISSUES_TRACK = "ISSUES_TRACK";
